### ISSUE TITLE
Timeout on on prem v10

### ISSUE THREAD

**Issue by rderewianko** [BadStreff/git2jss#5]
Hello!

While further testing this in prep for our go live. We've also tested it on v10.
I'm seeing an error through the CI runner hitting the webapp(hosted on the same server), and if i run it locally hitting the same server, or on the server hitting the webapp.

What it seems is aiosync is spawning too many connections in a short period. Which Jamv10 doesn't seem to like. I can confirm this on 10.0.0 and 10.1.1.

 I've gone ahead and added to mysql & tomcat threads and still experience the same error.

```
Traceback (most recent call last):
  File "sync.py", line 49, in upload_extension_attribute
    resp = await session.put(put_url, auth=auth, data=ET.tostring(template), headers=headers)
  File "/home/rderewianko/.local/lib/python3.5/site-packages/aiohttp/helpers.py", line 104, in __await__
    ret = yield from self._coro
  File "/home/rderewianko/.local/lib/python3.5/site-packages/aiohttp/client.py", line 277, in _request
    yield from resp.start(conn, read_until_eof)
  File "/home/rderewianko/.local/lib/python3.5/site-packages/aiohttp/client_reqrep.py", line 624, in start
    (message, payload) = yield from self._protocol.read()
  File "/home/rderewianko/.local/lib/python3.5/site-packages/aiohttp/streams.py", line 554, in read
    yield from self._waiter
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 266, in result
    raise CancelledError
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sync.py", line 159, in <module>
    loop.run_until_complete(main(args))
  File "uvloop/loop.pyx", line 1364, in uvloop.loop.Loop.run_until_complete
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "sync.py", line 145, in main
    await upload_extension_attributes(session, args.url, args.username, args.password)
  File "sync.py", line 31, in upload_extension_attributes
    responses = await asyncio.gather(*tasks)
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "sync.py", line 52, in upload_extension_attribute
    resp = await session.post(post_url, auth=auth, data=ET.tostring(template), headers=headers)
  File "/home/rderewianko/.local/lib/python3.5/site-packages/async_timeout/__init__.py", line 35, in __exit__
    self._do_exit(exc_type)
  File "/home/rderewianko/.local/lib/python3.5/site-packages/async_timeout/__init__.py", line 80, in _do_exit
    raise asyncio.TimeoutError
concurrent.futures._base.TimeoutError
```

There is a difference in the number of submissions before failure.
CI Runner - 63
Locally - 112

**Comment by badstreff** [comment]
Thanks for the heads up! I'll work on adding a param to set a limit to the max number of connections allowed with a sane default.

I'll also try to add some error checking so a retry attempt is made with a warning to the user.

**Comment by badstreff** [comment]
So I was able to reproduce the issue on the master branch by creating a bunch of dummy scripts.
`for i in {1..200}; do echo "exit 0" >> scripts/${i}.sh; done`
```
Traceback (most recent call last):
  File "./sync.py", line 103, in upload_script
    auth=auth) as resp:
  File "/Users/ajf023/.pyenv/versions/3.6.3/lib/python3.6/site-packages/aiohttp/client.py", line 690, in __aenter__
    self._resp = yield from self._coro
  File "/Users/ajf023/.pyenv/versions/3.6.3/lib/python3.6/site-packages/aiohttp/client.py", line 267, in _request
    conn = yield from self._connector.connect(req)
  File "/Users/ajf023/.pyenv/versions/3.6.3/lib/python3.6/site-packages/aiohttp/connector.py", line 389, in connect
    yield from fut
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./sync.py", line 159, in <module>
    loop.run_until_complete(main(args))
  File "uvloop/loop.pyx", line 1364, in uvloop.loop.Loop.run_until_complete
  File "./sync.py", line 144, in main
    await upload_scripts(session, args.url, args.username, args.password)
  File "./sync.py", line 91, in upload_scripts
    responses = await asyncio.gather(*tasks)
  File "./sync.py", line 111, in upload_script
    resp = await session.post(post_url, auth=auth, data=ET.tostring(template), headers=headers)
  File "/Users/ajf023/.pyenv/versions/3.6.3/lib/python3.6/site-packages/async_timeout/__init__.py", line 35, in __exit__
    self._do_exit(exc_type)
  File "/Users/ajf023/.pyenv/versions/3.6.3/lib/python3.6/site-packages/async_timeout/__init__.py", line 80, in _do_exit
    raise asyncio.TimeoutError
concurrent.futures._base.TimeoutError
```

Can you test the branch I created for issue#5 and let me know the results, I was able to successfully upload the scripts from this branch by creating a semaphore to make sure not too many connections were opened at once.

**Comment by rderewianko** [comment]
From my first test there were no errors posting to a JSS on V10. :D

**Comment by rderewianko** [comment]
Running in production seeing no errors with a limit :) 👍
